"""Playwright Test Agent — explores an API endpoint and generates/runs Playwright tests."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import requests
from openai import OpenAI
from rich.console import Console

sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from shared.config import load_config
from shared.logger import get_logger
from agents.playwright_test_agent.test_runner import TestRunner
from agents.playwright_test_agent.reporter import Reporter

PROMPT_TEMPLATE_PATH = Path(__file__).parent / "prompts" / "generate_tests.txt"
GENERATED_TESTS_PATH = Path(__file__).parent / "generated_tests.py"

logger = get_logger("playwright-test-agent")
console = Console()


class PlaywrightTestAgent:
    def __init__(self, target_url: str, config: dict):
        self.target_url = target_url
        self.config = config
        self.client = OpenAI(api_key=config["OPENAI_API_KEY"])
        self.model = config.get("OPENAI_MODEL", "gpt-4o-mini")
        self._exploration: dict = {}
        self._scenarios: list[dict] = []

    def explore(self) -> dict:
        console.print(f"[bold cyan]Exploring[/] {self.target_url}")
        try:
            resp = requests.get(self.target_url, timeout=10)
            resp.raise_for_status()
            body = resp.json()
        except requests.RequestException as exc:
            logger.error("Exploration failed", extra={"error": str(exc), "url": self.target_url})
            raise

        shape = {k: type(v).__name__ for k, v in body.items()} if isinstance(body, dict) else {"type": "array", "length": len(body)}
        self._exploration = {
            "url": self.target_url,
            "status_code": resp.status_code,
            "response_shape": shape,
            "sample": body,
        }
        console.print(f"[green]Explored[/] — status {resp.status_code}, fields: {list(shape.keys())}")
        logger.info("Exploration complete", extra=self._exploration)
        return self._exploration

    def generate_scenarios(self) -> list[dict]:
        if not self._exploration:
            self.explore()

        template = PROMPT_TEMPLATE_PATH.read_text()
        prompt = (
            template
            .replace("{target_url}", self.target_url)
            .replace("{method}", "GET")
            .replace("{response_shape}", json.dumps(self._exploration.get("response_shape", {}), indent=2))
        )

        console.print("[bold cyan]Generating[/] test scenarios via LLM…")
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
        )
        raw = response.choices[0].message.content.strip()

        try:
            self._scenarios = json.loads(raw)
        except json.JSONDecodeError:
            logger.error("LLM returned invalid JSON", extra={"raw": raw[:500]})
            raise ValueError(f"LLM did not return valid JSON. Raw output:\n{raw[:500]}")

        console.print(f"[green]Generated[/] {len(self._scenarios)} scenarios")
        return self._scenarios

    def scaffold_tests(self, scenarios: list[dict]) -> str:
        lines = [
            "# Auto-generated by PlaywrightTestAgent — do not edit manually",
            "import pytest",
            "import requests",
            "",
            f'TARGET_URL = "{self.target_url}"',
            "",
        ]

        for s in scenarios:
            fn_name = f"test_{s['name']}"
            expected_status = s["expected_status"]
            method = s.get("method", "GET").lower()
            input_data = s.get("input") or {}
            behavior = s.get("expected_behavior", "")

            params_arg = f"params={input_data!r}" if method == "get" and input_data else ""
            json_arg = f"json={input_data!r}" if method != "get" and input_data else ""
            call_args = ", ".join(filter(None, [f'"{self.target_url}"', params_arg, json_arg]))

            lines += [
                f"def {fn_name}():",
                f'    """{behavior}"""',
                f"    resp = requests.{method}({call_args}, timeout=10)",
                f"    assert resp.status_code == {expected_status}, f\"Expected {expected_status}, got {{resp.status_code}}\"",
                "",
            ]

        test_code = "\n".join(lines)
        GENERATED_TESTS_PATH.write_text(test_code)
        console.print(f"[green]Scaffolded[/] test file → {GENERATED_TESTS_PATH}")
        return test_code

    def run(self) -> dict:
        self.explore()
        self.generate_scenarios()
        self.scaffold_tests(self._scenarios)

        runner = TestRunner(str(GENERATED_TESTS_PATH))
        results = runner.run()

        reporter = Reporter(target_url=self.target_url, scenarios=self._scenarios, results=results)
        report = reporter.generate()

        console.print("[bold green]Done.[/] Reports written.")
        return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Playwright Test Agent")
    parser.add_argument("--url", required=True, help="Target API URL to test")
    args = parser.parse_args()

    cfg = load_config(required_keys=["OPENAI_API_KEY"])
    agent = PlaywrightTestAgent(target_url=args.url, config=cfg)
    agent.run()
